lib/chat_app_web/router.ex
defmodule ChatAppWeb.Router do
  use ChatAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ChatAppWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChatAppWeb do
    pipe_through :browser

    get "/", RoomController, :index
    resources "/rooms", RoomController, except: [:index]
    resources "/sessions", SessionController, only: [:new, :create]
    resources "/registration", RegistrationController, only: [:new, :create]
    delete "/sign_out", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChatAppWeb do
  #   pipe_through :api
  # end
end

lib/chat_app_web/views/layout_view.ex
defmodule ChatAppWeb.LayoutView do
  use ChatAppWeb, :view
end

lib/chat_app_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>ChatApp · Phoenix Framework</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-dark">
      <h3 class="my-0 mr-md-auto font-weight-normal">
        <%= link "Chat App", to: Routes.room_path(@conn, :index), class: "navbar-brand text-light" %>
      </h3>
      <%= if @signed_in? do %>
        <nav class="text-light my-2 my-md-0 mr-md-3">
          Signed in as: <strong><%= @current_user.username %> </strong>
        </nav>
        <%= link "Sign out", to: Routes.session_path(@conn, :delete), method: :delete, class: "btn btn-outline-primary" %>
      <% else %>
        <%= link "Sign up", to: Routes.registration_path(@conn, :new), class: "btn btn-outline-primary ml-md-3" %>
        <%= link "Login", to: Routes.session_path(@conn, :new), class: "btn btn-outline-info ml-md-3"%>
      <% end %>
    </div>

    <%= unless is_nil(get_flash(@conn, :info)) do %>
      <p class="alert alert-success" role="alert"><%= get_flash(@conn, :info) %></p>
    <% end %>
    <%= unless is_nil(get_flash(@conn, :error)) do %>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <% end %>

    <main role="main" class="container">
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/js/all.js"></script>
    <script> window.userToken = "<%= assigns[:user_token] %>"</script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>